run-connected debe ejecutar el Payload incluso si el usuario ya esta conectado (comportamiento esperado)
atscub/nautapy pull request #21
Opened 2023-01-15 22:40 UTC by lesclaz

Fixes #3

run-connected solo ejecuta el Payload si existe una sesion activa en nautapy.
agregue una llamada al metodo dispose de la clase NautaProtocol en cada excepcion dispara al crear la sesion y a la hora de cerrar sesion para que no exista un archivo de sesion cuando en realidad no hay sesion activa.

2023-03-04 19:44 UTC, lesclaz reviewed
Se puede adicionar un flag --strict para el caso en que se desee el comportamiento que tiene actualmente. :: HECHO

2023-05-22 19:17 UTC, atscub commented
Hola, gracias por el PR, no tengo mucho tiempo para mantener el proyecto por estos dias. Acerca de esto:

> Solucionado: **Cuando se ejecuta el comando run-connected y ya hay conexion a internet el comando falla.**
> 
> * [x]  El comportamiento apropiado debe ser ejecutar el Payload correctamente.
> * [x]  Se puede adicionar un flag `--strict` para el caso en que se desee el comportamiento que tiene actualmente.

Creo que es mejor invertir la logica y usar un flag `--reuse-connection` para el caso en que ya existe una conexion. De esta manera es **backward compatible**.

Puedes hacer el cambio?

Saludos.

2023-07-13 18:31 UTC, lesclaz commented
> Creo que es mejor invertir la logica y usar un flag `--reuse-connection` para el caso en que ya existe una conexion. De esta manera es **backward compatible**.

HECHO 👍

2023-07-19 08:32 UTC, atscub requested changes
Hay 24 archivos modificados (creo que cambiaste los accesos sin querer de 644 a 755). Puedes revertir esto tambien?

Gracias por la contribucion y espero poder integrarlo pronto.

2023-07-19 08:32 UTC, atscub commented on nautapy/cli.py
> +    else:
Falta checkear el flag `--reuse-connection`

```suggestion
    elif args.reuse_connection:
```

2023-07-19 08:32 UTC, atscub commented on nautapy/cli.py
> +    print("Sesión cerrada con éxito")
Si se reusa la conexion no debemos cerrar al final, porque algun otro proceso puede estar usando la conexion.

```suggestion
```

2023-07-19 23:42 UTC, lesclaz commented
Creo que si se debería cerrar sesión cuando se termine de ejecutar la tarea con `--reuse-connection`. De lo contrario ese flag no tiene ningún sentido, ya que solo debo ejecutar la tarea sin necesidad de llamar a nautapy.

2023-07-20 11:31 UTC, atscub commented
@lesclaz pasa una cosa interesante:
1. Por un lado, ahora que lo pienso mejor, creo que tu solucion inicial era mejor. En definitiva el problema era mas un bug que un feature.
2. Con respecto a cerrar la conexion. Que pasa si hay otra tarea usando tambien `run-connected` y le cierras la conexión? Y al mismo, que pasa si esta otra tarea termina primero y te cierra la conexion.

Sobre el 2do punto, una idea es contar las conexiones activas y cuando llegue a cero desconectar, pero esto es un poco tricky de implementar sin **race conditions**. Se te ocurre algo?

2023-07-20 13:33 UTC, lesclaz commented
> @lesclaz pasa una cosa interesante:
> 
> 1. Por un lado, ahora que lo pienso mejor, creo que tu solucion inicial era mejor. En definitiva el problema era mas un bug que un feature.

Creo que esta última tiene sus ventajas, lo que creo hay que mostrar un mensaje de **ya hay una conexión activa a internet, si aún así desea usar** `-run-connected` **agregue el flag** `--reuse-connection`

> 2. Con respecto a cerrar la conexion. Que pasa si hay otra tarea usando tambien `run-connected` y le cierras la conexión? Y al mismo, que pasa si esta otra tarea termina primero y te cierra la conexion.
> 
¿La idea original de `-run-connect` no es abrir una conexión, ejecutar la tarea y cuando termine dicha tarea, cerrar la conexión? Te pongo un ejemplo del porqué yo lo utilizaría aún teniendo una conexión activa:
- Acabo de terminar de trabajar con internet, pero ejecutó un `sudo apt update` para ver que hay y resulta que hay actualizaciones por 680 MB, como no quiero esperar a que se descargue todo, uso `-run-connect` para una vez termine la actualización se cierre la conexión automáticamente. De no ser así, no usaría esta funcionalidad, me limito a solo lanzar el comando por terminal.
> 
> Sobre el 2do punto, una idea es contar las conexiones activas y cuando llegue a cero desconectar, pero esto es un poco tricky de implementar sin **race conditions**. Se te ocurre algo?

No se de que hablas, si me pudieras dar contexto o una doc inicial (como una url de wikipedia sobre el tema) lo intentaría estudiar, pero creo que esto sería más adecuado para la función proxy que quieres implementar que para `-run-connect`.

2023-07-20 13:57 UTC, lesclaz commented
Algo que si veo interesante de implementar es la posibilidad de agregar tareas. Ejemplo: `nauta -run-connect sudo apt upgrade`, luego recuerdo que tenía que descargar un archivo, lo ideal sería abrir una nueva terminal y ejecutar `nauta -run-connect --add-task wget https://url.to.file` así una vez termine de actualizar el sistema pase a descargar el archivo y luego si cierre sesión.
No se que te parece la idea.
Es necesario implementar una pila de tareas para esto y cuando termine de ejecutar la tarea actual revise dicha pila, si quedan tareas por ejecutar, las ejecuta, en caso contrario, cierra la conexión.

2023-07-20 17:21 UTC, atscub commented
> ¿La idea original de `-run-connect` no es abrir una conexión, ejecutar la tarea y cuando termine dicha tarea, cerrar la conexión? Te pongo un ejemplo del porqué yo lo utilizaría aún teniendo una conexión activa:
> 
> * Acabo de terminar de trabajar con internet, pero ejecutó un `sudo apt update` para ver que hay y resulta que hay actualizaciones por 680 MB, como no quiero esperar a que se descargue todo, uso `-run-connect` para una vez termine la actualización se cierre la conexión automáticamente. De no ser así, no usaría esta funcionalidad, me limito a solo lanzar el comando por terminal.

Sí, exactamente esa fue la razón para crear run-connected, a veces queria descargar algo de madrugada entonces para no tener que esperar es una buena opcion. El problema que yo digo, es supon que llamas dos veces a run-connect con diferentes comandos. Cualquiera de los dos que termine primero te cierra la conexion y falla la otra descarga. Como manejar eso?

Claro entiendo que es un caso bastante raro y puede que no tenga sentido emplear tiempo en eso (al menos por ahora).

> No se de que hablas, si me pudieras dar contexto o una doc inicial (como una url de wikipedia sobre el tema) lo intentaría estudiar, pero creo que esto sería más adecuado para la función proxy que quieres implementar que para `-run-connect`.

Seria mas adecuado sí. Lo dificil es sincronizar procesos diferentes. Pero cuando tienes un proxy o servidor tienes un solo proceso, asi que es mas sencillo.

2023-07-20 17:24 UTC, atscub commented
> Algo que si veo interesante de implementar es la posibilidad de agregar tareas. Ejemplo: `nauta -run-connect sudo apt upgrade`, luego recuerdo que tenía que descargar un archivo, lo ideal sería abrir una nueva terminal y ejecutar `nauta -run-connect --add-task wget https://url.to.file` así una vez que termina de actualizar el sistema pasa a descargar el archivo y luego cierra sesión. No se que te parece la idea. Es necesario implementar una pila de tareas para esto y cuando termine de ejecutar la tarea actual revise dicha pila, si quedan tareas por ejecutar, las ejecuta, en caso contrario, cierra la conexión.

Sí, esto es una alternativa a lo que te propuse. Aunque me gusta mas que los dos procesos vayan en paralelo. De todas formas creo que no vale la pena el esfuerzo, porque es un caso de uso bastante extremo.

Pero si te animas, bien por mi.

2023-07-20 17:24 UTC, atscub commented
Manda la solucion final para mezclar. Por cierto fijate que todavia quedan 3 archivos con permisos cambiados.

2023-07-20 18:34 UTC, lesclaz commented
> > Algo que si veo interesante de implementar es la posibilidad de agregar tareas. Ejemplo: `nauta -run-connect sudo apt upgrade`, luego recuerdo que tenía que descargar un archivo, lo ideal sería abrir una nueva terminal y ejecutar `nauta -run-connect --add-task wget https://url.to.file` así una vez que termina de actualizar el sistema pasa a descargar el archivo y luego cierra sesión. No se que te parece la idea. Es necesario implementar una pila de tareas para esto y cuando termine de ejecutar la tarea actual revise dicha pila, si quedan tareas por ejecutar, las ejecuta, en caso contrario, cierra la conexión.
> 
> 
> 
> Sí, esto es una alternativa a lo que te propuse. Aunque me gusta mas que los dos procesos vayan en paralelo. De todas formas creo que no vale la pena el esfuerzo, porque es un caso de uso bastante extremo.
> 
> 
> 
> Pero si te animas, bien por mi.

Creo que se puede hacer aún con procesos en paralelo, solo hay que discutir la mejor opción. Luego creo otro pull request o un issue con una idea

2023-07-21 09:56 UTC, atscub requested changes
Se ve bien. Solo un pequeño detalle. Al unir las partes del `cmd` creo que debe quedar un espacio (ver las sugerencias a continuación).

2023-07-21 09:56 UTC, atscub commented on nautapy/cli.py
> +            os.system("".join(args.cmd))
```suggestion
            os.system(" ".join(args.cmd))
```

2023-07-21 09:56 UTC, atscub commented on nautapy/cli.py
> +        os.system("".join(args.cmd))
```suggestion
        os.system(" ".join(args.cmd))
```

2023-07-21 10:02 UTC, merged

2023-07-21 10:06 UTC, atscub commented
Mezclado :rocket::tada::tada:

Es lindo crear algo y que otros lo usen y contribuyan. Gracias!